artifacts_root : artifacts

data_ingestion:
     root_dir : artifacts
     source_url : https://github.com/entbappy/Branching-tutorial/raw/refs/heads/master/samsumdata.zip
     local_data_file : artifacts/data.zip
     unzip_dir : artifacts

data_validation:
    root_dir : artifacts
    STATUS_FILE : artifacts/validate_status.txt
    ALL_REQUIRED_FILES : ["train", "test", "validation"]

data_transformation:
    root_dir : artifacts
    data_path : artifacts/samsum_dataset
    tokenizer_name : google/pegasus-cnn_dailymail

model_trainer:
    root_dir : artifacts
    data_path : artifacts/dataset
    model_ckpt : google/pegasus-cnn_dailymail